WITH T0 AS (
    SELECT 
        --目前只挑有用到欄位
        T.ID,
        T.EQPID,
        T.STIME,
        CASE WHEN T.ETIME = 'NULL' THEN NULL
        ELSE T.ETIME 
        END AS ETIME,
        T.OPSTATUS,
        T.DURATION + 1 AS DURATION,
        T.isDel 
        FROM dbo.TMESEQPRUNTIME1 T
    --查詢isDel 不等於false
        WHERE isDel = '0'
        AND EQPID = '3'
    --查詢日期參數當日的資料
        AND SUBSTRING(STIME, 1, 4) + '-' + SUBSTRING(STIME, 5, 2) + '-' + SUBSTRING(STIME, 7, 2) = '${P_DATE}'
),
-- T1 查詢兩張圖表會用到的欄位
T1 AS (SELECT 
        --目前只挑有用到欄位
        T0.*,
        --將STIME 以及 ETIME 的HHMMSS substring 出來以利後續CTE(T2)用來轉換成秒數形式
        CAST(SUBSTRING(STIME, 9, 2) + SUBSTRING(STIME, 11, 2) + SUBSTRING(STIME, 13, 2) AS VARCHAR) AS STIME1,
        CAST(SUBSTRING(ETIME, 9, 2) + SUBSTRING(ETIME, 11, 2) + SUBSTRING(ETIME, 13, 2) AS VARCHAR) AS ETIME1,
        --STIME字串轉換成日期格式
        CAST(SUBSTRING(STIME, 1, 4) + '-' + SUBSTRING(STIME, 5, 2) + '-' + SUBSTRING(STIME, 7, 2) + ' ' + 
             SUBSTRING(STIME, 9, 2) + ':' + SUBSTRING(STIME, 11, 2) + ':' + SUBSTRING(STIME, 13, 2) AS DATETIME) AS STARTTime,
        --ETIME字串轉換成日期格式
        CAST(SUBSTRING(ETIME, 1, 4) + '-' + SUBSTRING(ETIME, 5, 2) + '-' + SUBSTRING(ETIME, 7, 2) + ' ' + 
             SUBSTRING(ETIME, 9, 2) + ':' + SUBSTRING(ETIME, 11, 2) + ':' + SUBSTRING(ETIME, 13, 2) AS DATETIME) AS ENDTime
    FROM 
        T0
    --查詢isDel 不等於false
),T2 AS (
SELECT 
 ID, 
 EQPID, 
 STIME, 
 CASE WHEN ETIME IS NULL THEN 
FORMAT( DATEADD(SECOND,DURATION,STARTTime) ,'yyyyMMddhhmmss') 
 ELSE ETIME 
 END AS ETIME, 
 OPSTATUS, 
 DURATION, 
 isDel,
 STIME1,
 CASE WHEN ETIME1 IS NULL THEN 
 CAST(SUBSTRING(FORMAT( DATEADD(SECOND,DURATION,STARTTime) ,'yyyyMMddhhmmss') , 9, 2) + SUBSTRING(FORMAT( DATEADD(SECOND,DURATION,STARTTime) ,'yyyyMMddhhmmss') , 11, 2) + SUBSTRING(FORMAT( DATEADD(SECOND,DURATION,STARTTime) ,'yyyyMMddhhmmss') , 13, 2) AS VARCHAR)
 ELSE ETIME1 END AS ETIME1,
 STARTTime,
 CASE WHEN ENDTime IS NULL THEN FORMAT( DATEADD(SECOND,DURATION,STARTTime) ,'yyyy-MM-dd hh:mm:ss')
 ELSE ENDTime END AS ENDTime
FROM T1)
--T3 是用於將HHMMSS格式轉換成秒數格式，以利於堆積圖判斷時間軸順序
,T3 AS (
SELECT 
CAST(ID AS VARCHAR) AS ID , 
EQPID, 
STIME, 
ETIME,
OPSTATUS,
DURATION,
isDel,
 --將HHMMSS格式，轉換成秒數格式
SUBSTRING(STIME1,1,2)*60*60 + SUBSTRING(STIME1,3,2)*60 + SUBSTRING(STIME1,5,2) AS STIME_SEC,
SUBSTRING(ETIME1,1,2)*60*60 + SUBSTRING(ETIME1,3,2)*60 + SUBSTRING(ETIME1,5,2) AS ETIME_SEC,
STARTTime,
ENDTime
FROM T2
WHERE ETIME <STIME)
-- 列出下一筆的starttime
,T4 AS (
    SELECT 
        T3.*,
        LEAD(STIME_SEC) OVER (PARTITION BY EQPID ORDER BY STIME_SEC) AS NEXT_STIME_SEC,
        LEAD(STIME) OVER (PARTITION BY EQPID ORDER BY STIME) AS NEXT_STIME,
        LEAD(STARTTime) OVER (PARTITION BY EQPID ORDER BY STARTTime) AS NEXT_STARTTime
    FROM T3
)
--CTE(T5):此CTE內資料為設備之間間隔的數據，STATUS 皆為停機用於填補設備狀態紀錄之間的空白時間，將其標記為停機時間
,T5 AS (
SELECT 
    CAST(ID AS VARCHAR) + 'gap' AS ID, 
    EQPID,
    --將E
    ETIME AS STIME,
    -- 來補滿兩筆資料結束時間以及下一筆的開始時間，若>0則將NEXT_STIME 為ETIME
    NEXT_STIME AS ETIME,
    '0' AS OPSTATUS,
    DATEDIFF(SECOND,ENDTime,NEXT_STARTTime) AS DURATION,
    isDel,
    ETIME_SEC AS STIME_SEC,
    NEXT_STIME_SEC AS ETIME_SEC,
    ENDTime AS STARTTime,
    NEXT_STARTTime AS ENDTime
FROM T4
WHERE DATEDIFF(SECOND, ENDTime, NEXT_STARTTime) > 0
), T6 AS(
SELECT * FROM T3
UNION ALL 
SELECT * FROM T5
WHERE ETIME_SEC > STIME_SEC
-- 計算稼動、等待、異常 狀態的總時間
),TB1
AS(
SELECT 
    -- 計算稼動、等待、異常 狀態的總時間
        SUM(CASE WHEN REMARK1 = N'運轉' THEN Duration ELSE 0 END) AS OperationTime,
        SUM(CASE WHEN REMARK1 = N'等待' THEN Duration ELSE 0 END) AS WaitingTime,
        SUM(CASE WHEN REMARK1 = N'異常' THEN Duration ELSE 0 END) AS Downtime
    FROM T6
    LEFT JOIN TMIMDCDE
        ON T6.OPSTATUS = TMIMDCDE.CODE
    AND SUBSTRING(STIME, 1, 4) + '-' + SUBSTRING(STIME, 5, 2) + '-' + SUBSTRING(STIME, 7, 2) = '2024-10-29'
),TB2 AS(
    -- 計算稼動率
SELECT 
        ROUND((OperationTime + WaitingTime) * 1.0 / NULLIF((OperationTime + WaitingTime + Downtime), 0), 2) AS Availability
FROM TB1),TB3 AS(
SELECT
SUM(T6.Duration) AS Total_duration,
    SUM(T6.Duration) * 1.0 / SUM(SUM(T6.Duration)) OVER () AS DurationPercentage,
    T6.OPSTATUS,
    REMARK1
FROM T6
LEFT JOIN TMIMDCDE
ON T6.OPSTATUS = TMIMDCDE.CODE
LEFT JOIN TMIMEQUIP
    ON T6.[EQPID] = TMIMEQUIP.[ASSETNO]
GROUP BY REMARK1,T6.OPSTATUS)
--加入空字串以利排序
,TB4(ID,EQPID,STIME,ETIME,OPSTATUS,DURATION,isDel,STIME_SEC,ETIME_SEC,STARTTime,ENDTime,REMARK1,EQUIP,EQUIPNAME,OPSTATUS1,Total_duration,DurationPercentage,Availability) 
AS (
    SELECT NULL,'3',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,N'運轉',NULL,NULL,'1',NULL,NULL,TB2.Availability
    FROM TB2
    UNION ALL
    SELECT NULL,'3',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,N'等待',NULL,NULL,'2',NULL,NULL,TB2.Availability
    FROM TB2
    UNION ALL
    SELECT NULL,'3',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,N'異常',NULL,NULL,'3',NULL,NULL,TB2.Availability
    FROM TB2
    UNION ALL
    SELECT NULL,'3',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,N'未開機',NULL,NULL,'0',NULL,NULL,TB2.Availability
    FROM TB2
    UNION ALL
    SELECT NULL,'3',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,N'未定義',NULL,NULL,'-1',NULL,NULL,TB2.Availability
    FROM TB2
)
SELECT * FROM TB4
UNION ALL 
SELECT T6.*, T7.REMARK1, T8.EQUIP, T8.EQUIPNAME, T6.OPSTATUS + '-' + CAST(COUNT(*) OVER (PARTITION BY T6.OPSTATUS ORDER BY T6.STARTTime) AS VARCHAR) AS OPSTATUS1 ,TB3.Total_duration,TB3.DurationPercentage,TB2.*
FROM T6
LEFT JOIN TMIMDCDE T7
ON T6.OPSTATUS = T7.CODE 
LEFT JOIN TMIMEQUIP T8
ON T6.[EQPID] = T8.ASSETNO 
LEFT JOIN TB3
ON T6.[OPSTATUS]= TB3.[OPSTATUS],TB2
ORDER BY STARTTime ASC