WITH DAT AS(
SELECT TOP(1)
YYYYMMDD
-- 正式資料改用以下條件
-- FORMAT(GETDATE(),'yyyyMMdd') AS YYYYMMDD 
FROM VMIMFR_ASCHE_CO
WHERE DEPT = '6'
ORDER BY YYYYMMDD DESC
), TAB0 AS(
SELECT 
LINE,
MODEL,
STIME,
ETIME,
CHKSTATUS,
T1.YYYYMMDD
FROM VMIMFR_ASCHE_CO T1
JOIN DAT T2 ON T1.YYYYMMDD = T2.YYYYMMDD 
WHERE DEPT = '6'
), TAB1 AS(
SELECT
LINE,
MODEL,
RIGHT(REPLICATE('0', 6) + CAST(STIME AS NVARCHAR), 6) AS STIME,
RIGHT(REPLICATE('0', 6) + CAST(ETIME AS NVARCHAR), 6) AS ETIME,
CHKSTATUS,
YYYYMMDD
FROM TAB0
), TAB2 AS(
SELECT
RANK() OVER(PARTITION BY LINE ORDER BY STIME) AS SER,
LINE,
MODEL,
SUBSTRING(STIME,1,2)*60*60+SUBSTRING(STIME,3,2)*60+SUBSTRING(STIME,5,2) AS STIME_SEC,
SUBSTRING(ETIME,1,2)*60*60+SUBSTRING(ETIME,3,2)*60+SUBSTRING(ETIME,5,2) AS ETIME_SEC,
CHKSTATUS,
YYYYMMDD
FROM TAB1
)
SELECT
CONCAT(LINE,SER) AS COMBO,
SER,
LINE,
MODEL,
STIME_SEC,
ETIME_SEC,
ETIME_SEC-STIME_SEC AS PERIOD,
CHKSTATUS,
DATEADD(second,STIME_SEC,CONVERT(DATETIME,YYYYMMDD)) AS STARTTIME,
DATEADD(second,ETIME_SEC,CONVERT(DATETIME,YYYYMMDD)) AS ENDTIME
FROM TAB2
WHERE LINE = '${P_LINE}'