SELECT 
LINEID,
EQPID,
STIME,
ETIME,
OPSTATUS,
Duration,
REMARK1,
EQUIPNAME,
EQUIP
FROM [dbo].[TMESEQPRUNTIME] T1 
LEFT JOIN [dbo].[TMIMDCDE] T2 
ON T1.[OPSTATUS] = REVERSE(T2.[CODE])
LEFT JOIN [dbo].[TMIMEQUIP] T3
ON T1.[EQPID] = T3.[ASSETNO]
-- 使用子查询来获取最大 STIME
WHERE STIME = (
    SELECT MAX(STIME) 
    FROM [dbo].[TMESEQPRUNTIME]
)
GROUP BY 
LINEID,
EQPID,
ETIME,
OPSTATUS,
Duration,
REMARK1,
EQUIPNAME,
EQUIP